//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poco
{
    using System;
    using System.Collections.Generic;
    
    public partial class brokers_Trades_List
    {
        public int broker_id { get; set; }
        public string Broker_FullName { get; set; }
        public Nullable<int> share_amount { get; set; }
    }
}
