//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poco
{
    using System;
    using System.Collections.Generic;
    
    public partial class shares_prices
    {
        public int share_id { get; set; }
        public Nullable<decimal> price { get; set; }
        public System.DateTime time_start { get; set; }
        public Nullable<System.DateTime> time_end { get; set; }
    
        public virtual share share { get; set; }
    }
}
