//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poco
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TradingPlatformContext : DbContext
    {
        public TradingPlatformContext()
            : base("name=TradingPlatformContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<broker> brokers { get; set; }
        public virtual DbSet<company> companies { get; set; }
        public virtual DbSet<currency> currencies { get; set; }
        public virtual DbSet<place> places { get; set; }
        public virtual DbSet<share> shares { get; set; }
        public virtual DbSet<shares_prices> shares_prices { get; set; }
        public virtual DbSet<stock_exchanges> stock_exchanges { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<trade> trades { get; set; }
        public virtual DbSet<brokers_Trades_List> brokers_Trades_List { get; set; }
    }
}
